function interfaz()
clc; 

    interfaz = InterfazClass;
    paciente = DatosPaciente;
    serial = Serial;
    variables = Variables;

    figure('Units','pixels','Position',[200 200 1000 690]);
         
        %
        %%TEXT EDIT
        interfaz.datosPacienteLista = [0;0;0;0];
        datosPacienteTexto = {'Nombre: ', 'Edad: ', 'Sexo: ', 'Altura: ', 'Peso: '};
        for i = 1:5
            interfaz.datosPacienteLista(i) = uicontrol('Style', 'text',... 
                                        'unit','pix',... 
                                        'position',[80 590-i*30 280 30],...
                                        'fontsize',12,...
                                        'horizontalAlignment', 'left',...
                                        'String', datosPacienteTexto{i});
        end
       
        prompt={'Nombre Completo', 'Edad', 'Sexo(M o F)', 'Altura(Cm)', 'Peso(Kg)' };
        fields = {'nombre','edad', 'sexo', 'altura', 'peso'};
        pacienteDialog = inputdlg(prompt, 'Datos del paciente', [1 40; 1 15; 1 15; 1 15; 1 15]);
        
        if ~isempty(pacienteDialog)              
           pacienteDialog = cell2struct(pacienteDialog,fields);
           paciente.nombre = pacienteDialog.nombre;
           paciente.edad = str2num(pacienteDialog.edad);
           paciente.sexo = pacienteDialog.sexo;
           paciente.altura = str2num(pacienteDialog.altura);
           paciente.peso = str2num(pacienteDialog.peso);
        end
             
        
        interfaz.titlesVariablesLista = [0;0;0;0];
        interfaz.variablesLista = [0;0;0;0];
        editTexto = {'BPM', 'SPO2', 'Temperatura', 'Conductancia'};
        for i = 1:2
            interfaz.titlesVariablesLista(i) = uicontrol('Style', 'text',... 
                                        'unit','pix',... 
                                        'position',[420+i*150 170 130 30],...
                                        'fontsize',14,...
                                        'String', editTexto{i});
        end
        for i = 1:2
            interfaz.variablesLista(i) = uicontrol('Style', 'text',... 
                                        'unit','pix',... 
                                        'position',[420+i*150 140 130 30],...
                                        'fontsize',14);
        end
        for i = 3:4
            interfaz.titlesVariablesLista(i) = uicontrol('Style', 'text',... 
                                        'unit','pix',... 
                                        'position',[420+(i-2)*150 90 130 30],...
                                        'fontsize',14,...
                                        'String', editTexto{i});
        end
        for i = 3:4
            interfaz.variablesLista(i) = uicontrol('Style', 'text',... 
                                        'unit','pix',... 
                                        'position',[420+(i-2)*150 60 130 30],...
                                        'fontsize',14);
        end
        
        interfaz.estadoDispositivo = uicontrol('Style', 'text',... 
                   'unit','pix',... 
                   'position',[100 110 190 20],...
                   'fontsize',11,...
                   'String', 'Dispositivo Desconectado');
       
               
               
       %
       %%TIMERS
        interfaz.escaneoTimer = timer ('Name', 'timerEscanear',...
                          'Period', 1,...
                          'ExecutionMode', 'fixedSpacing',...
                          'BusyMode', 'drop',...
                          'TimerFcn', @(o, e) escaneo(serial, variables)); 

          interfaz.variablesTimer = timer ('Name', 'timerPintarVariables',...
                   'Period', 3,...
                   'ExecutionMode', 'fixedSpacing',...
                   'BusyMode', 'drop');
                          
        
        %
        %%PUSH BUTTON
        interfaz.conectarButton = uicontrol('Style','pushbutton',...
                  'Position', [80 150 110 50],...
                  'String', 'Conectar',...
                  'fontsize',13,...
                  'Callback',{@conectar_pushbutton_callback, serial, interfaz});
        
        interfaz.desconectarButton = uicontrol('Style','pushbutton',...
                  'Position', [200 150 110 50],...
                  'String', 'Desconectar',...
                  'fontsize',13,...
                  'Callback',{@desconectar_pushbutton_callback, serial, interfaz});
        
        interfaz.inicioButton = uicontrol('Style','pushbutton',...
                  'Position', [80 270 110 50],...
                  'String', 'Inicio',...
                  'fontsize',13,...
                  'Callback',{@inicio_pushbutton_callback, variables, interfaz});
           
        interfaz.pararButton = uicontrol('Style','pushbutton',...
                  'Position', [200 270 110 50],...
                  'String', 'Parar',...
                  'fontsize',13,...
                  'Callback',{@parar_pushbutton_callback,interfaz});
              
        
        %
        %%SET
        set(interfaz.datosPacienteLista(1),'String', strcat({'Nombre: '}, paciente.nombre));
        set(interfaz.datosPacienteLista(2),'String', strcat({'Edad: '}, num2str(paciente.edad)));
        set(interfaz.datosPacienteLista(3),'String', strcat({'Sexo: '}, paciente.sexo));
        set(interfaz.datosPacienteLista(4),'String', strcat({'Altura: '}, num2str(paciente.altura)));
        set(interfaz.datosPacienteLista(5),'String', strcat({'Peso: '}, num2str(paciente.peso)));
        
        %
        %%FICHERO
        nombreFichero = strcat(paciente.nombre, '.txt');
        interfaz.fichero=fopen(nombreFichero,'w');
        fprintf(interfaz.fichero,'Nombre:  %s \t', paciente.nombre); 
        fprintf(interfaz.fichero,'Edad:  %d \t', paciente.edad); 
        fprintf(interfaz.fichero,'Sexo:  %s \t', paciente.sexo); 
        fprintf(interfaz.fichero,'Altura:  %d \t', paciente.altura); 
        fprintf(interfaz.fichero,'Peso:  %d \t', paciente.peso); 
 end


